spring:
  application:
    name: game-api
  data:
    mongodb:
      host: localhost
      port: 27017
      database: "game"

server:
  port: 8080

logging:
  file:
    name: ./game-service.log
  level:
    root: INFO
    com.setleauge: DEBUG
  pattern:
    #    console: "%d{ISO8601} %highlight(%-5level) %yellow(%C{1.}): %msg%n%throwable"
    file: "%d %p %c{1.} [%t] %m%n"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html