apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway-api
  name: gateway-api
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: gateway-api
  type: NodePort